add function
yamadaab/todo_list pull request #2
Opened 2021-03-05 09:51 UTC by yamadaab

2021-03-09 06:10 UTC, komagata requested changes
add functionだとどんなものにも当てはまるのでPRのタイトルとして（レビューするチームメイトにからみて）適切なものを考えてみてください〜

2021-03-09 06:10 UTC, komagata commented on todo.html
> +            return count >= 2
ここのインデントが少ないかもです〜

2021-03-09 06:10 UTC, komagata commented on todo.html
> +              this.loadTodo()
ここのインデントが多すぎるみたいです。

2021-03-09 08:28 UTC, yamadaab commented on todo.html
> +            return count >= 2
すみません、全角が入ってました。半角に修正しました。

2021-03-09 08:28 UTC, yamadaab commented on todo.html
> +              this.loadTodo()
すみません、スペース２つに修正しました。

2021-03-09 11:19 UTC, komagata requested changes

2021-03-09 11:19 UTC, komagata commented on todo.html
> +            return count >= 2
```suggestion
              return count >= 2
```

こうかも？です〜

2021-03-10 03:44 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-03-13 03:02 UTC, merged